config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :contractors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contractor.rb
class Contractor < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_action :set_contractor, only: [:show, :edit, :update, :destroy]

  # GET /contractors
  # GET /contractors.json
  def index
    @contractors = Contractor.all
  end

  # GET /contractors/1
  # GET /contractors/1.json
  def show
  end

  # GET /contractors/new
  def new
    @contractor = Contractor.new
  end

  # GET /contractors/1/edit
  def edit
  end

  # POST /contractors
  # POST /contractors.json
  def create
    uploaded_io = params[:contractor][:file]
    filepath = Rails.root.join('public', uploaded_io.original_filename)

    upload_file(filepath, uploaded_io)

    puts contractor_params
    @contractor = Contractor.new(contractor_params)
    @contractor.file = uploaded_io.original_filename     
    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: 'Contractor was successfully created.' }
        format.json { render :show, status: :created, location: @contractor }
      else
        format.html { render :new }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contractors/1
  # PATCH/PUT /contractors/1.json
  def update
    uploaded_io = params[:contractor][:file]
    filepath = Rails.root.join('public', uploaded_io.original_filename)

    upload_file(filepath, uploaded_io)

    puts contractor_params
    @contractor = Contractor.find(params[:id])
    @contractor.file = uploaded_io.original_filename
      if @contractor.update(contractor_params)
        format.html { redirect_to @contractor, notice: 'Contractor was successfully updated.' }
        format.json { render :show, status: :ok, location: @contractor }
      else
        format.html { render :edit }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
  end


  def upload_file(filepath, uploaded_io)
    File.open(filepath, 'wb') do |file|
      file.write(uploaded_io.read)
    end
  end

  # DELETE /contractors/1
  # DELETE /contractors/1.json
  def destroy
    @contractor.destroy
    respond_to do |format|
      format.html { redirect_to contractors_url, notice: 'Contractor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contractor
      @contractor = Contractor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contractor_params
      params.require(:contractor).permit(:name, :cv, :rate)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company, :start_date, :end_date, :contractor_ID)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/contractors/_form.html.erb
<%= form_with(model: contractor, local: true) do |form| %>
  <% if contractor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contractor.errors.count, "error") %> prohibited this contractor from being saved:</h2>

      <ul>
      <% contractor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cv %>
    <%= form.text_area :cv %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.text_field :rate %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contractors/edit.html.erb
<h1>Editing Contractor</h1>

<%= render 'form', contractor: @contractor %>

<%= link_to 'Show', @contractor %> |
<%= link_to 'Back', contractors_path %>

app/views/contractors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contractors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cv</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contractors.each do |contractor| %>
      <tr>
        <td><%= contractor.name %></td>
        <td><%= contractor.cv %></td>
        <td><%= contractor.rate %></td>
        <td><%= contractor.file %></td>
        <td><%= link_to contractor.file, contractor.file %></td>
        <td><%= link_to 'Show', contractor %></td>
        <td><%= link_to 'Edit', edit_contractor_path(contractor) %></td>
        <td><%= link_to 'Destroy', contractor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contractor', new_contractor_path %>

app/views/contractors/new.html.erb
<h1>New Contractor</h1>

<%= render 'form', contractor: @contractor %>

<%= link_to 'Back', contractors_path %>

app/views/contractors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contractor.name %>
</p>

<p>
  <strong>Cv:</strong>
  <%= @contractor.cv %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @contractor.rate %>
</p>

<%= link_to 'Edit', edit_contractor_path(@contractor) %> |
<%= link_to 'Back', contractors_path %>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
  <%= form.label :contractor_ID %><br />
  <%= form.select :contractor_ID, options_for_select(Contractor.all.map{|s|[s.name, s.id]}) %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Contractor id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.company %></td>
        <td><%= job.start_date %></td>
        <td><%= job.end_date %></td>
        <td><%= job.contractor_ID %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @job.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @job.end_date %>
</p>

<p>
  <strong>Contractor id:</strong>
  <%= @job.contractor_ID %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Benzoonrails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>